### PR TITLE
Hidden flag to disable address normalization for debugging

### PR DESCRIPTION
**Pull request by marselester**
As per @brancz, the address normalization should happen on the Parca Server side.

> We definitely want to remove the normalization from Parca Agent if possible, as the pprof profiles it generates are currently broken with standard tooling (eg. regular pprof).

With a flag, we should be able to test the changes without interfering with release cycles on both sides.

### CODE REVIEW

**Comment by brancz** [comment]
I like this idea a lot!

**Review by brancz — APPROVED** [review]

**Comment by zdyj3170101136** [comment]
is this will fix https://github.com/parca-dev/parca-agent/issues/1187?

**Comment by zdyj3170101136** [comment]
you must merge this pr https://github.com/parca-dev/parca-agent/pull/1196/files.
to let the extract debuginfo have enough information to compute base address.

**Comment by brancz** [comment]
Not yet, this is just for experimenting with different approaches, but the goal is to normalize on the server-side, yes!

**Pull request merged**
