### PR TITLE
libbpf: Upgrade to 05f94ddbb837f5

### PR DESCRIPTION
**Pull request by javierhonduco**
Our current version is from early 2023. Let's update to a version close to the one used by libbpfgo's CI from mid this year.

```
commit 05f94ddbb837f5f4b3161e341eed21be307eaa04 (HEAD)
Author: Andrii Nakryiko <andrii@kernel.org>
Date:   Tue Jul 11 09:43:03 2023 -0700

    sync: latest libbpf changes from kernel

    Syncing latest libbpf commits from kernel repository.
    Baseline bpf-next commit:   c628747cc8800cf6d33d09f7f42c8b6f91e64dc7
    Checkpoint bpf-next commit: a3e7e6b17946f48badce98d7ac360678a0ea7393
    Baseline bpf commit:        496720b7cfb6574a8f6f4d434f23e3d1e6cfaeb9
    Checkpoint bpf commit:      496720b7cfb6574a8f6f4d434f23e3d1e6cfaeb9

    Andrii Nakryiko (1):
      libbpf: Fix realloc API handling in zero-sized edge cases

    John Sanpe (1):
      libbpf: Remove HASHMAP_INIT static initialization helper

     src/hashmap.h | 10 ----------
     src/libbpf.c  | 15 ++++++++++++---
     src/usdt.c    |  5 ++++-
     3 files changed, 16 insertions(+), 14 deletions(-)

    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
```

### CODE REVIEW

**Comment by javierhonduco** [comment]
This didn't run the tests... We should fix this

**Comment by javierhonduco** [comment]
https://github.com/parca-dev/parca-agent/blob/0b98a9252277eebb8f49c308c14bc31ba58cc4ea/.github/workflows/build.yml#L42 🤔

**Comment by kakkoyun** [comment]
Does this version match the libbpf-go version?

**Review by kakkoyun — CHANGES_REQUESTED** [review]
> Does this version match the libbpfgo version?

https://github.com/parca-dev/parca-agent/blob/main/go.mod => https://github.com/aquasecurity/libbpfgo/tree/v0.5.1-libbpf-1.2

https://github.com/aquasecurity/libbpfgo/tree/v0.5.1-libbpf-1.2 => https://github.com/libbpf/libbpf/tree/1728e3e4bef0e138ea95ffe62163eb9a6ac6fa32

so we need to be on 1728e3e4bef0e1

**Comment by javierhonduco** [comment]
Superseded by https://github.com/parca-dev/parca-agent/pull/2306

**Pull request closed without merging**
