### PR TITLE
feat(metadata): cache label sets

### LINKED ISSUE #890: relabelling: cache the result of relabeling functions
I think this can totally be a follow up, but relabel configs are pure functions meaning as long as relabel configs don’t change the produced labelset doesn’t change. Therefore for any given process we need to only relabel once and can from there cache the result.

_Originally posted by @brancz in https://github.com/parca-dev/parca-agent/pull/887#pullrequestreview-1137015174_

cc @maxbrunet

### PR DESCRIPTION
**Pull request by maxbrunet**
* 1 cache per profiler (key: `pid`, value: `labelSet`)
* lazy caching happens when profiler requests labels
* no caching happens when request comes from UI as:
  * this does not happen often
  * this would require convention from `label.Labels` to `model.LabelSet`
  * UI requests labels for all processes on the system, they are not all profiled if idled, which would unnecessarily inflate the cache
* all caches are invalidated on config reload
* cache keys for individual PIDs are invalidated on updates from service discovery (via a hook function)
* otherwise, cache keys expire if not accessed for more than 10 minutes

Closes #890

### CODE REVIEW

**Comment by javierhonduco** [comment]
Hi! Thanks for the PR! Will take a look later today

**Review by Sylfrena — APPROVED** [review]

**Comment by kakkoyun** [comment]
I have been checking why actually the PR is failing, but I don't have any reasonable explanations. We haven't changed anything concerning secrets. Yet the container action fails.

**Comment by maxbrunet** [comment]
@kakkoyun please #934 for the CI, we'll ignore that until fixed

@javierhonduco do you still want to add a review?

Something came to my mind, I need to add a read lock when calling the hooks

**Comment by kakkoyun** [comment]
@maxbrunet Thanks for the context. I was about to go nuts 😅 

I'm happy to merge this if others are okay as well.

**Review by kakkoyun — APPROVED** [review]

**Comment by kakkoyun** [comment]
> LGTM! Will let it bake for 1 day in the [demo environment](https://demo.parca.dev/)

Have you deployed it? Or shall we merge and deploy a version?

**Comment by javierhonduco** [comment]
@kakkoyun Meant to do this once we merge it :)

**Comment by javierhonduco** [comment]
One small comment about something we need to revisit in the Agent as a whole is that caching PIDs can be problematic due to them being reused.

We don't have to tackle this in this PR but it's something that we should be aware of

**Comment by maxbrunet** [comment]
> One small comment about something we need to revisit in the Agent as a whole is that caching PIDs can be problematic due to them being reused.

We should be able to add the `starttime` field of `/proc/[pid]/stat` to the cache key: `awk '{print $23}' "/proc/${pid}/stat"`

**Comment by kakkoyun** [comment]
> > One small comment about something we need to revisit in the Agent as a whole is that caching PIDs can be problematic due to them being reused.
> 
> We should be able to add the `starttime` field of `/proc/[pid]/stat` to the cache key: `awk '{print $23}' "/proc/${pid}/stat"`
> 
> https://pkg.go.dev/github.com/prometheus/procfs#ProcStat.StartTime

It's a good idea!

**Pull request merged**
