### PR TITLE
Fix unwinder loading on 6.8 kernels

### PR DESCRIPTION
**Pull request by umanwizard**
See comments, and mailing list thread linked therein, for details. Before this change, recent kernels (6.8 and later) cannot verify the native unwinder, because improvements in the precision of register bounds tracking cause an explosion in state space resulting in exceeding the limit of 1 million instructions processed per load.

This commit works around that issue, as the comment in the code explains.

### CODE REVIEW

**Review by kakkoyun — APPROVED** [review]
LGTM 🚀 

Wow, interesting.

Happy to merge when CI is green!

**Comment by kakkoyun** [comment]
Is the failure of the native unwinder integration tests on arm64 expected? That should have worked, but the rest could fail.

**Comment by umanwizard** [comment]
No, it's not expected. I need to look into that, thanks.

**Comment by umanwizard** [comment]
OK, this finally. @kakkoyun and @brancz , can you please have another look?

We can't use function calls; everything has to be inlined in order to work on old kernels. But if we let clang/llvm inline the function, it will optimize it away...

I solved this problem by just using inline volatile asm, which the compiler won't optimize. It's an ugly solution, but it seems to work.

**Pull request merged**
