### PR TITLE
Produce statically linked binaries

### LINKED ISSUE #332: Statically link or remove libc from binaries
- To static link: `go build --ldflags '-linkmode external -extldflags "-static"` or `go build -ldflags="-extldflags=-static"`
- To (potentially) remove: `go build -tags netgo` `!! This might not be possible with CGO and this could change the behaviour of DNS resolution, so we should test it.`

> User/group resolution, and the non-DNS aspects for host resolution, are code that only exists in the libc, and the way glibc implements those is by dynamically loading libraries based on config files. Unless you explicitly opt out (use pure-Go implementations that imitate some of the behavior), if you use either of those facilities, you will get a dynamically linked glibc.

ref: 
https://ops.tips/notes/glibc-golang-learnings/
https://www.arp242.net/static-go.html

### PR DESCRIPTION
**Pull request by kakkoyun**
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

Fixes #332 #328 

# TODO

* [x] Clean up Dockerfiles
* [x] Make sure CGO cross-compilation works (using Goreleaser)
* [x] Test against arm64

### CODE REVIEW

**Comment by brancz** [comment]
Does this mean we can also get rid of copying them in our dockerfile here? https://github.com/parca-dev/parca-agent/blob/0c05f0048b6773011bcbeeb26221e6e8cadb5e0e/Dockerfile#L45-L52

**Comment by kakkoyun** [comment]
@brancz Good call. Let me make check that.

**Review by brancz — APPROVED** [review]
😍 lgtm

**Comment by javierhonduco** [comment]
Thanks again for implementing this, just learned that ASAN doesn't run on statically linked binaries

```
github.com/parca-dev/parca-agent/pkg/discovery
github.com/parca-dev/parca-agent/cmd/parca-agent
# github.com/parca-dev/parca-agent/cmd/parca-agent
/usr/lib/golang/pkg/tool/linux_amd64/link: running clang failed: exit status 1
/usr/bin/ld: /usr/lib64/clang/14.0.0/lib/linux/libclang_rt.asan-x86_64.a(asan_linux.cpp.o): in function `__asan::AsanDoesNotSupportStaticLinkage()':
(.text+0x37): undefined reference to `_DYNAMIC'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

so `build-dyn` unblocked me 🎉

**Pull request merged**
