### PR TITLE
Add crane to determine digest of the container image

### PR DESCRIPTION
**Pull request by kakkoyun**
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

xref: https://github.com/parca-dev/parca/pull/1041

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
lgtm

**Comment by kakkoyun** [comment]
@cpanato quay seems failing I'm trying to debug it https://github.com/parca-dev/parca-agent/runs/6440132726?check_suite_focus=true

It's an authorization error but it has the write access. Have you seen any similar errors before?
```Error: POST https://quay.io/v2/parca/parca/blobs/uploads/: UNAUTHORIZED: access to the requested resource is not authorized; map[]
[39](https://github.com/parca-dev/parca-agent/runs/6440132726?check_suite_focus=true#step:10:39)
main.go:52: error during command execution: POST https://quay.io/v2/parca/parca/blobs/uploads/: UNAUTHORIZED: access to the requested resource is not authorized; map[]
[40](https://github.com/parca-dev/parca-agent/runs/6440132726?check_suite_focus=true#step:10:40)
make: *** [Makefile:237: push-signed-quay-container] Error 1```

**Comment by cpanato** [comment]
> @cpanato quay seems failing I'm trying to debug it https://github.com/parca-dev/parca-agent/runs/6440132726?check_suite_focus=true
> 
> It's an authorization error but it has the write access. Have you seen any similar errors before?
> 
> ```
> [39](https://github.com/parca-dev/parca-agent/runs/6440132726?check_suite_focus=true#step:10:39)
> main.go:52: error during command execution: POST https://quay.io/v2/parca/parca/blobs/uploads/: UNAUTHORIZED: access to the requested resource is not authorized; map[]
> [40](https://github.com/parca-dev/parca-agent/runs/6440132726?check_suite_focus=true#step:10:40)
> make: *** [Makefile:237: push-signed-quay-container] Error 1```
> ```

humm, looks like it is not getting the login we did in a step before.

**Comment by cpanato** [comment]
@kakkoyun i will try to reproduce that in a test project and check it, 🐻 with me

**Comment by cpanato** [comment]
able to reproduce https://github.com/cpanato/testing-ci-providers/runs/6442136152?check_suite_focus=true, checking a fix

**Comment by cpanato** [comment]
the issue looks like is related to the `podman login` if i use `docker login` instead that works https://github.com/cpanato/testing-ci-providers/runs/6442149954?check_suite_focus=true

for the ci job, i think that is okay to replace to docker login because we don't use podman for anything related with quay

cc @kakkoyun

**Pull request merged**
