### PR TITLE
Update podman

### PR DESCRIPTION
**Pull request by javierhonduco**
Currently CI is broken
```
docker pull quay.io/containers/podman:v4.7.2@sha256:f3671cf897e2a8745c926ff2720a990fb350815a85d5b6fd58f4d5cb58ef458d
Error response from daemon: manifest for quay.io/containers/podman@sha256:f3671cf897e2a8745c926ff2720a990fb350815a85d5b6fd58f4d5cb58ef458d not found: manifest unknown: manifest unknown
```

### CODE REVIEW

**Comment by javierhonduco** [comment]
Not sure yet why it got out of sync

**Comment by brancz** [comment]
the podman team sadly removes "old" container images as soon as a new one is pushed, it's actually very annoying

**Review by brancz — APPROVED** [review]

**Comment by javierhonduco** [comment]
Triggered an update but didn't get the latest hash. Unfortunately, I think there's something broken in the update process because we had different hashes for podman

**Comment by javierhonduco** [comment]
Ugh 

```
Error response from daemon: manifest for quay.io/containers/podman@sha256:f3671cf897e2a8745c926ff2720a990fb350815a85d5b6fd58f4d5cb58ef458d not found: manifest unknown: manifest unknown
```

**Comment by javierhonduco** [comment]
Nvm I just had forgotten to add both changes... 😓

**Comment by kakkoyun** [comment]
This happens frequently, exactly as @brancz described.

**Comment by maxbrunet** [comment]
My recommendation is too simply remove the digest (parca-dev/.github#27), that was done in the Parca repo.

Renovate caches results from the registries, that's likely why it was not aware of the latest yet

**Pull request merged**
