### PR TITLE
debuginfo: Add pure Go ELF Writer to extract debug information

### PR DESCRIPTION
**Pull request by kakkoyun**
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

## Test Plan

- [x] `sudo ./scripts/local-run.sh`
- [x]  `make dev/up && tilt up`
  - Visual check

### CODE REVIEW

**Comment by brancz** [comment]
This is very very nice! I’m curious, do you think it would be possible to instead of writing the debuginfos to a separate file first to immediately write it to the uploader? We’ve seen so many issues with the agent crashing nodes by over utilizing the empty dir volume in Kubernetes that I’ve been wondering if we can avoid it entirely. Nothing to necessarily do in this PR, but food for thought maybe.

**Comment by kakkoyun** [comment]
> This is very very nice! I’m curious, do you think it would be possible to instead of writing the debuginfos to a separate file first to immediately write it to the uploader? We’ve seen so many issues with the agent crashing nodes by over utilizing the empty dir volume in Kubernetes that I’ve been wondering if we can avoid it entirely. Nothing to necessarily do in this PR, but food for thought maybe.

@brancz This is totally possible. And it's actually something I plan. It just requires some changes in existing architecture, and this PR is already too large. I'll send consecutive PR to remove the need for interim files.

**Comment by brancz** [comment]
Sounds good!

**Comment by v-thakkar** [comment]
Really wonderful work! Having an in-house package will be super helpful in the future too. So I'm excited about it. Looking good :clap:

**Pull request merged**
