### PR TITLE
pkg/convert: support convert collapsed async profiler to pprof

### PR DESCRIPTION
**Pull request by zdyj3170101136**
### Why?
support convert collapsed format of async profiler output to pprof

### What?
use a state machine to parse the file.

### CODE REVIEW

**Comment by brancz** [comment]
In which situation would we use this instead of the JFR->pprof converter?

**Comment by zdyj3170101136** [comment]
> In which situation would we use this instead of the JFR->pprof converter?

just to Provide additional options

**Comment by brancz** [comment]
If we're not using this, I don't think we should have this code here.

**Comment by brancz** [comment]
Agreed with @v-thakkar

**Pull request closed without merging**
