### PR TITLE
profiler: Cache seen stack trace ids in user-space

### PR DESCRIPTION
**Pull request by marselester**
@kakkoyun did you mean something like this when describing stack id misses https://github.com/parca-dev/parca-agent/issues/390? Note, there is no thought put into concurrency or cache invalidation yet.

### CODE REVIEW

**Comment by kakkoyun** [comment]
> @kakkoyun did you mean something like this when describing stack id misses #390? Note, there is no thought put into concurrency or cache invalidation yet.

It's a good start. The idea is to eliminate the need to re-reading stack addresses from the eBPF map. We should still count them. 

We also need to consider what to do with the stack traces of eBPF maps. Shall we have another seen map in the kernel space to let the eBPF program know so that it won't bother to store the stack trace? 

So overall idea is that when we have stable hashes of the stack traces (which we should have), we don't need to keep syncing the stack traces themselves constantly. This could be a pre-mature optimization. We should make sure we got this right.

**Comment by marselester** [comment]
That's a great idea!

So we can read from the `counts` BPF map on each iteration, check whether there is a stack trace cached in the user space using `stack hash` field:

- cache hit -- no need to read from the `stack_traces` BPF map
- cache miss -- read user/kernel space stack traces from the `stack_traces` BPF map

I assume that user and kernel space memory addresses should be combined to create `stack hash`.

```
stack hash = hash([ 0xdeadbeef; 0x123abcde; ...; 0x597be95a; 0xae5ee03; ... ]) = 'abcd'
```

The `counts` BPF map.

| { pid; userStackID; kernelStackID } | stack hash | seen
| ---                                 | ---        | ---
| { 10342; 1253; 0234 }               | abcd       | 45

The `stack_traces` BPF map.

| stack ID | memory addresses
| ---      | ---
| 1253     | [ 0xdeadbeef; 0x123abcde; ... ]
| 0234     | [ 0x597be95a; 0xae5ee03; ... ]

> Shall we have another seen map in the kernel space to let the eBPF program know so that it won't bother to store the stack trace?

Yeah, the `seen` BPF map can be added on the next optimization iteration 👍. Though I am not sure what strategy to use to invalidate the `seen` cache (BPF map) so it won't grow unbounded.

| stack hash | v
| ---        | ---
| abcd       | true

---

Perhaps the `stack_traces` BPF map should be indexed by `stack hash` so the `seen` BPF map won't be needed, also we might reduce a number of syscalls when reading the user and kernel space stack traces in one go.

**Comment by marselester** [comment]
Hm, if there are multiple processes running the same program, perhaps there could be hash collisions. We could add PID to the hash 🤔.

```
stack hash = hash([ 10342; 0xdeadbeef; 0x123abcde; ...; 0x597be95a; 0xae5ee03; ... ]) = 'abcd'
```

**Comment by marselester** [comment]
After reading `cpu.bpf.c` code I realized that there is already stack trace hashing used in DWARF stack walking `int user_stack_id_dwarf;`, so I added hashes for kernel space and user space (frame pointer method?).

```c
int user_stack_id_fp;
int kernel_stack_id_fp;
```

**Comment by javierhonduco** [comment]
Hi @marselester! Thanks a lot for this!

Regarding the stack hashing, it's not necessary to add the frame pointer-based stack or kernel hashes, as the values returned by [`bpf_get_stackid`](https://man7.org/linux/man-pages/man7/bpf-helpers.7.html) is already a [hash](https://github.com/torvalds/linux/blob/3d7cb6b04c3f3115719235cc6866b10326de34cd/kernel/bpf/stackmap.c#L231)! 😄 

While I really appreciate the intent behind this PR, as definitely this project could be optimised to use fewer CPU cycles and memory, I think caching stack ids could result in difficult-to-debug issues, as well as it would increase the memory footprint of the agent, as the cache will use extra memory. 

I would be happy to add the extra complexity if this were a hotspot, but it seems like ~2.7% of the CPU cycles are spent here, which I am not sure if it would be worth it

https://pprof.me/de88b35

image

That being said, there are lots of areas we could improve in the agent when it comes to performance, and I would be happy to help you find something you might find interesting to work on.

For example:
- 5% of the CPU cycles are spent allocating memory in `compress/flate.NewWriter`
- We spent over 20% of the cycles searching in the GC, searching for object `runtime.scanobject`. This might mean that we make to many allocations that could be optimised, or that perhaps we could reduce the number of pointers we have
- We spent a disproportionate amount of cycles[ finding metadata for systemd units](https://github.com/parca-dev/parca-agent/issues/1037)

Hope this makes sense! Looking forward to seeing your contributions! ✨

**Comment by marselester** [comment]
Thank you! Let me see if I can tackle the issues you've proposed...

> it's not necessary to add the frame pointer-based stack or kernel hashes

Silly me, I didn't know that :D

**Comment by javierhonduco** [comment]
No worries at all! 😄

**Pull request closed without merging**
