### PR TITLE
pkg/debuginfo: Add plt symbol

### PR DESCRIPTION
**Pull request by zdyj3170101136**
see https://github.com/parca-dev/parca/pull/2491

### CODE REVIEW

**Review by kakkoyun — APPROVED** [review]
LGTM ❤️ 💚 💙 💛 💜

**Review by v-thakkar — CHANGES_REQUESTED** [review]
Thanks for handling this @zdyj3170101136 . The change looks good to me. But it'll be nice to have a test case for this section in elfwriter_test.

Edit: Just mentioning you here , in case you missed this :)

**Comment by kakkoyun** [comment]
> Thanks for handling this @zdyj3170101136 . The change looks good to me. But it'll be nice to have a test case for this section in elfwriter_test.
> 
> Edit: Just mentioning you here , in case you missed this :)

@zdyj3170101136 Do you want to take care of this? We can merge it then.

**Comment by kakkoyun** [comment]
> > Thanks for handling this @zdyj3170101136 . The change looks good to me. But it'll be nice to have a test case for this section in elfwriter_test.
> > Edit: Just mentioning you here , in case you missed this :)
> 
> @zdyj3170101136 Do you want to take care of this? We can merge it then.

@zdyj3170101136 Friendly ping 😊

**Comment by v-thakkar** [comment]
@zdyj3170101136 Feel free to add a file that contains .plt symbol in the testdata for the tests you need to write for this PR. Let us know if we can help with anything regarding that.

**Pull request merged**
