### PR TITLE
debug-info: Use child process reaper for more reliable external command execution

### PR DESCRIPTION
**Pull request by kakkoyun**
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

Used https://github.com/containerd/containerd/blob/main/sys/reaper/reaper_unix.go

Could be a mitigation for https://github.com/parca-dev/parca-agent/issues/184

cc @derekparker

### CODE REVIEW

**Comment by brancz** [comment]
If I'm understanding this correctly the two things this does is:

1) Continuously reap zombie processes while Parca Agent continues to run.
2) Reap all processes when Parca Agent shuts down.

If that's correct, then lgtm :+1:

**Comment by kakkoyun** [comment]
> If I'm understanding this correctly the two things this does is:
> 
> 1. Continuously reap zombie processes while Parca Agent continues to run.

Yes :+1: 

> 2. Reap all processes when Parca Agent shuts down.
I'll just add the necessary line :)

**Comment by derekparker** [comment]
Hm, I'd be kind of be surprised if we're not reaping these processes already. We run them with `cmd.CombinedOutput()` which internally uses `cmd.Run` which also internally calls `cmd.Wait()` which should wait until the process has actually exited so the `Wait` call itself should reap the child.

Have we observed these commands creating zombie processes in the wild? I saw the associated issue but I'd be surprised if executing these commands causes pid exhaustion or something else to lock up the system. Difficult to say without more information though. We should ask the reporter of the original issue to test this patch if possible.

**Comment by kakkoyun** [comment]
@derekparker Exactly as you said. We don't for sure. This is just mitigation for a hunch, in case we're exhausting PID space. We make sure we clean as much as possible. This doesn't have a major downside if you don't have major concerns I will go with it. Until we hear back from them

**Comment by brancz** [comment]
We sadly don't push container images on PRs/branches, so I would be ok with merging to make it as easy as possible for the user to try.

**Comment by derekparker** [comment]
> @derekparker Exactly as you said. We don't for sure. This is just mitigation for a hunch, in case we're exhausting PID space. We make sure we clean as much as possible. This doesn't have a major downside if you don't have major concerns I will go with it. Until we hear back from them

SGTM!

**Pull request merged**
