### PR TITLE
Add check for Arm64 DWARF Expressions

### PR DESCRIPTION
**Pull request by Sylfrena**

### CODE REVIEW

**Comment by Sylfrena** [comment]
Rebase on latest, updated testdata repo

**Comment by brancz** [comment]
What's left so that this is still WIP?

**Comment by Sylfrena** [comment]
So sorry, didn't see your question earlier. I want to rebase this branch on latest testdata changes but haven't gotten to thoroughly check all the new uploaded binaries.

**Review by brancz — COMMENTED** [review]
lgtm but @kakkoyun and/or @gnurizen should have a look as well

**Review by kakkoyun — APPROVED** [review]
LGTM 💯

**Comment by brancz** [comment]
Outdated since #2958

**Pull request closed without merging**
