### PR TITLE
Add version flag

### PR DESCRIPTION
**Pull request by kakkoyun**
```shell
$ parca-agent --version
> parca-agent, version  (commit: 7ff593d3d399e778d446e24759f35ddafb4bcdc6, date: 2023-04-12T15:18:42Z), arch: amd64
```

### Summary
🚀♻️📝

Added a `--version` flag and improved build info logging in `parca-agent`.

> _Show me the `--version` of your doom_
> _The build info is your final tomb_
> _Refactor the code in the `main` function_
> _You can't escape the metal destruction_

### Walkthrough
* Add a `Version` flag to show the application version with the `--version` option ([link](https://github.com/parca-dev/parca-agent/pull/1552/files?diff=unified&w=0#diff-57833d176ed681886b67a7fa2e4dc2f68d5e00cb1db269e7854fb3dafb45f54eR100))
* Move the code to fetch and assign the build info variables (`commit`, `date`, `goArch`) from the `run` function to the `main` function in `cmd/parca-agent/main.go`, to avoid duplication and make the build info available for the `Version` flag ([link](https://github.com/parca-dev/parca-agent/pull/1552/files?diff=unified&w=0#diff-57833d176ed681886b67a7fa2e4dc2f68d5e00cb1db269e7854fb3dafb45f54eL191-R210), [link](https://github.com/parca-dev/parca-agent/pull/1552/files?diff=unified&w=0#diff-57833d176ed681886b67a7fa2e4dc2f68d5e00cb1db269e7854fb3dafb45f54eL298-L320))
* Check and handle the `Version` flag in the `main` function in `cmd/parca-agent/main.go`, to print the version information and exit the program if the flag is set ([link](https://github.com/parca-dev/parca-agent/pull/1552/files?diff=unified&w=0#diff-57833d176ed681886b67a7fa2e4dc2f68d5e00cb1db269e7854fb3dafb45f54eL200-R233))
* Move the log message for the initialization of the parca-agent from the `run` function to the `main` function in `cmd/parca-agent/main.go`, to match the location of the build info assignment ([link](https://github.com/parca-dev/parca-agent/pull/1552/files?diff=unified&w=0#diff-57833d176ed681886b67a7fa2e4dc2f68d5e00cb1db269e7854fb3dafb45f54eL200-R233), [link](https://github.com/parca-dev/parca-agent/pull/1552/files?diff=unified&w=0#diff-57833d176ed681886b67a7fa2e4dc2f68d5e00cb1db269e7854fb3dafb45f54eL298-L320))

### CODE REVIEW

**Comment by javierhonduco** [comment]
Looks great. Lol at the AI-generated text. Could you please add the output of `--version`? Thanks!

**Comment by kakkoyun** [comment]
> Looks great. Lol at the AI-generated text. Could you please add the output of `--version`? Thanks!

`parca-agent, version  (commit: 7ff593d3d399e778d446e24759f35ddafb4bcdc6, date: 2023-04-12T15:18:42Z), arch: amd64`

**Comment by javierhonduco** [comment]
Is it expected that the version is empty?

**Comment by kakkoyun** [comment]
> Is it expected that the version is empty?

Do you see this case? We just print package-level variables and inject those during build time. In theory, you can have a custom build command to skip injecting and it could be empty.

**Comment by javierhonduco** [comment]
Ah, ok, guess they are empty in this example. Would be nice to indicate that they are unavailable but not a biggie

**Pull request merged**
